---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      name: python-app
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: techcloudifyme/python-mysql:v1
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOSTNAME
          value: "mysql"            
        - name: DB_PORT
          value: "3306"            
        - name: DB_NAME
          value: "employee"            
        - name: DB_USERNAME
          value: "root"            
        - name: DB_PASSWORD
          value: "dbpassword11"  