apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-mysql
  template:
    metadata:
      labels:
        app: springboot-mysql
    spec:
      containers:
      - name: springboot-mysql
        image: techcloudifyme/springboot-mysql:v2
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: host
